services:
  backend:
    image: sferehi18/football-api:latest
    container_name: football-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  frontend:
    image: sferehi18/football-web:latest
    container_name: football-web
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

