services:

  backend:

    build: ./api-tfg

    container_name: football-api

    ports:
      - "8000:8000"

    env_file:
      - ./.env

    volumes:
      - ./api-tfg/app/data:/app/app/data
      - ./api-tfg/app/models:/app/app/models

    restart: always


  frontend:

    build: ./frontend-tfg

    container_name: football-web

    ports:
      - "80:80"

    depends_on:
      - backend

    restart: always